services:

  vegetable-backend:
    image: vegetable-backend:1.0
    container_name: vegetable-backend

    ports:
      - "8080:8080"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/vegetable_db
      SPRING_DATASOURCE_USERNAME: veguser
      SPRING_DATASOURCE_PASSWORD: StrongPassword

    restart: unless-stopped
