import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter, Link, NavLink, Route, Routes, useNavigate, useParams } from 'react-router-dom'
import './styles.css'

const api = async (path, options = {}) => {
  const token = localStorage.getItem('veg_token')
  const headers = { ...(options.body ? { 'Content-Type': 'application/json' } : {}), ...(options.headers || {}) }
  if (token) headers.Authorization = `Bearer ${token}`
  const res = await fetch(path, { ...options, headers })
  const text = await res.text(); let data = null
  try { data = text ? JSON.parse(text) : null } catch { data = text }
  if (!res.ok) throw new Error(data?.message || data?.error || `Request failed (${res.status})`)
  return data
}
const money = n => `₹${Number(n || 0).toFixed(2)}`
const user = () => { try { return JSON.parse(localStorage.getItem('veg_user') || 'null') } catch { return null } }
const tokenClaims = token => { try { const p = token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/'); return JSON.parse(atob(p)) } catch { return {} } }

function Layout() {
  const navigate = useNavigate(), u = user(), [cartCount,setCartCount] = useState(0)
  useEffect(() => { if (u) api('/api/cart').then(c => setCartCount(c.reduce((s,x)=>s+x.quantity,0))).catch(()=>{}) }, [u?.email])
  const logout=()=>{localStorage.clear();navigate('/')}
  return <><header className="topbar"><Link className="brand" to="/">🥬 FreshBasket</Link><nav><NavLink to="/shop">Shop</NavLink>{u&&<NavLink to="/orders">Orders</NavLink>}{u&&<NavLink to="/addresses">Addresses</NavLink>}{u?.role==='SELLER'&&<NavLink to="/seller">Seller</NavLink>}{u?.role==='ADMIN'&&<NavLink to="/admin">Admin</NavLink>}{u?<><Link to="/cart">Cart ({cartCount})</Link><button className="linkbtn" onClick={logout}>Logout</button></>:<><NavLink to="/login">Login</NavLink><NavLink className="signup" to="/register">Create account</NavLink></>}</nav></header><main className="page"><Routes><Route path="/" element={<Home/>}/><Route path="/shop" element={<Shop setCartCount={setCartCount}/>}/><Route path="/login" element={<Login/>}/><Route path="/register" element={<Register/>}/><Route path="/cart" element={<Cart setCartCount={setCartCount}/>}/><Route path="/orders" element={<Orders/>}/><Route path="/orders/:id" element={<OrderDetail/>}/><Route path="/addresses" element={<Addresses/>}/><Route path="/seller" element={<Seller/>}/><Route path="/admin" element={<Admin/>}/><Route path="*" element={<NotFound/>}/></Routes></main><footer>FreshBasket · Vegetable marketplace</footer></>
}
function Home(){return <section className="hero"><div><span className="eyebrow">FRESH • LOCAL • SIMPLE</span><h1>Fresh vegetables,<br/><em>delivered simply.</em></h1><p>Browse fresh produce, build your cart and track every order from one clean marketplace.</p><Link className="primary" to="/shop">Shop vegetables →</Link></div><div className="hero-art">🥕<span>🍅</span><b>🥦</b><i>🥔</i></div></section>}
function Login(){const [form,setForm]=useState({email:'',password:''}),[err,setErr]=useState(''),nav=useNavigate();const submit=async e=>{e.preventDefault();setErr('');try{const d=await api('/api/auth/login',{method:'POST',body:JSON.stringify(form)});const claims=tokenClaims(d.token);localStorage.setItem('veg_token',d.token);localStorage.setItem('veg_user',JSON.stringify({email:form.email,role:claims.role||claims.roles?.[0]||'CUSTOMER'}));nav('/shop')}catch(x){setErr(x.message)}};return <AuthCard title="Welcome back" subtitle="Sign in to continue shopping."><form onSubmit={submit}>{field('Email','email',form.email,v=>setForm({...form,email:v}))}{field('Password','password',form.password,v=>setForm({...form,password:v}))}{err&&<div className="error">{err}</div>}<button className="primary full">Sign in</button></form><p className="muted center">New here? <Link to="/register">Create an account</Link></p></AuthCard>}
function Register(){const [form,setForm]=useState({fullName:'',email:'',phone:'',password:''}),[err,setErr]=useState(''),nav=useNavigate();const submit=async e=>{e.preventDefault();setErr('');try{await api('/api/auth/register',{method:'POST',body:JSON.stringify(form)});nav('/login')}catch(x){setErr(x.message)}};return <AuthCard title="Create your account" subtitle="Start shopping fresh produce today."><form onSubmit={submit}>{field('Full name','text',form.fullName,v=>setForm({...form,fullName:v}))}{field('Email','email',form.email,v=>setForm({...form,email:v}))}{field('Phone','tel',form.phone,v=>setForm({...form,phone:v}))}{field('Password','password',form.password,v=>setForm({...form,password:v}))}{err&&<div className="error">{err}</div>}<button className="primary full">Create account</button></form></AuthCard>}
function AuthCard({title,subtitle,children}){return <div className="auth"><div className="card"><span className="eyebrow">FRESHBASKET</span><h2>{title}</h2><p className="muted">{subtitle}</p>{children}</div></div>}
function field(label,type,value,onChange){return <label>{label}<input required type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Shop({setCartCount}){const [products,setProducts]=useState([]),[cats,setCats]=useState([]),[q,setQ]=useState(''),[cat,setCat]=useState(''),[loading,setLoading]=useState(true),[err,setErr]=useState('');const load=async()=>{setLoading(true);try{const d=await api(`/api/products/search?keyword=${encodeURIComponent(q)}${cat?'&category='+encodeURIComponent(cat):''}&inStock=true&page=0&size=50&sortBy=name&direction=asc`);setProducts(d.content||d.products||[])}catch(x){setErr(x.message)}finally{setLoading(false)}};useEffect(()=>{api('/api/products/categories').then(setCats).catch(()=>{});load()},[]);const add=async p=>{if(!localStorage.getItem('veg_token')){alert('Please sign in first.');return}try{await api(`/api/cart/add?productId=${p.id}&quantity=1`,{method:'POST'});const c=await api('/api/cart');setCartCount(c.reduce((s,x)=>s+x.quantity,0))}catch(x){alert(x.message)}};return <section><div className="sectionhead"><div><span className="eyebrow">MARKET</span><h2>Fresh produce</h2></div></div><div className="filters"><input placeholder="Search vegetables..." value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()}/><select value={cat} onChange={e=>{setCat(e.target.value)}}><option value="">All categories</option>{cats.map(c=><option key={c}>{c}</option>)}</select><button className="secondary" onClick={load}>Search</button></div>{err&&<div className="error">{err}</div>}{loading?<p>Loading fresh produce…</p>:<div className="grid">{products.map(p=><article className="product" key={p.id}><div className="produce">{p.name.toLowerCase().includes('tomato')?'🍅':p.name.toLowerCase().includes('potato')?'🥔':'🥬'}</div><div className="productbody"><div className="tag">{p.category}</div><h3>{p.name}</h3><p className="muted">{p.description}</p><div className="row"><strong>{money(p.price)}</strong><span className="stock">{p.quantity??p.stockQuantity} available</span></div><button className="primary full" onClick={()=>add(p)}>Add to cart</button></div></article>)}</div>}</section>}
function Cart({setCartCount}){const [items,setItems]=useState([]),[addresses,setAddresses]=useState([]),[addressId,setAddressId]=useState(''),[msg,setMsg]=useState(''),nav=useNavigate();const load=async()=>{try{setItems(await api('/api/cart'));setAddresses(await api('/api/addresses'))}catch(x){setMsg(x.message)}};useEffect(()=>{load()},[]);const update=async(i,q)=>{try{await api(`/api/cart/${i.id}?quantity=${q}`,{method:'PUT'});load();setCartCount((await api('/api/cart')).reduce((s,x)=>s+x.quantity,0))}catch(x){setMsg(x.message)}};const remove=async i=>{await api(`/api/cart/${i.id}`,{method:'DELETE'});load();setCartCount((await api('/api/cart')).reduce((s,x)=>s+x.quantity,0))};const total=items.reduce((s,i)=>s+(i.product?.price||i.price||0)*i.quantity,0);const checkout=async()=>{if(!addressId){setMsg('Select a delivery address.');return}try{const o=await api(`/api/orders?addressId=${addressId}`,{method:'POST'});setCartCount(0);nav(`/orders/${o.id}`)}catch(x){setMsg(x.message)}};return <section><div className="sectionhead"><div><span className="eyebrow">YOUR BAG</span><h2>Shopping cart</h2></div></div>{msg&&<div className="error">{msg}</div>}{!items.length?<div className="empty card">Your cart is empty. <Link to="/shop">Browse vegetables</Link></div>:<div className="cartlayout"><div className="card">{items.map(i=><div className="cartitem" key={i.id}><div className="mini">🥬</div><div className="grow"><b>{i.product?.name||'Product'}</b><small>{money(i.product?.price||i.price)}</small></div><div className="qty"><button onClick={()=>update(i,Math.max(1,i.quantity-1))}>−</button><span>{i.quantity}</span><button onClick={()=>update(i,i.quantity+1)}>+</button></div><button className="linkbtn danger" onClick={()=>remove(i)}>Remove</button></div>)}</div><aside className="summary card"><h3>Checkout</h3><div className="total"><span>Total</span><strong>{money(total)}</strong></div><label>Delivery address<select value={addressId} onChange={e=>setAddressId(e.target.value)}><option value="">Choose address</option>{addresses.map(a=><option key={a.id} value={a.id}>{a.fullName||a.city} — {a.city}</option>)}</select></label>{!addresses.length&&<Link to="/addresses">Add an address first</Link>}<button className="primary full" onClick={checkout}>Place order</button></aside></div>}</section>}
function Orders(){const [orders,setOrders]=useState([]);useEffect(()=>{api('/api/orders').then(setOrders).catch(()=>{})},[]);return <section><span className="eyebrow">ACCOUNT</span><h2>My orders</h2><div className="list">{orders.map(o=><Link className="ordercard" to={`/orders/${o.id}`} key={o.id}><div><b>Order #{o.id}</b><small>{new Date(o.createdAt).toLocaleString()}</small></div><span className={`status ${String(o.status).toLowerCase()}`}>{o.status}</span></Link>)}{!orders.length&&<div className="empty card">No orders yet.</div>}</div></section>}
function OrderDetail(){const {id}=useParams(),[o,setO]=useState(null),[err,setErr]=useState('');useEffect(()=>{api(`/api/orders/${id}`).then(setO).catch(x=>setErr(x.message))},[id]);if(err)return <div className="error">{err}</div>;if(!o)return <p>Loading order…</p>;return <section><Link to="/orders">← Back to orders</Link><div className="detailhead"><div><span className="eyebrow">ORDER</span><h2>#{o.id}</h2></div><span className={`status ${String(o.status).toLowerCase()}`}>{o.status}</span></div><div className="card"><h3>Items</h3>{(o.items||[]).map(i=><div className="line" key={i.id||i.orderItemId}><span>{i.product?.name||i.productName} × {i.quantity}</span><strong>{money((i.price||i.product?.price)*i.quantity)}</strong></div>)}</div></section>}
function Addresses(){const [list,setList]=useState([]),[form,setForm]=useState({fullName:'',phone:'',addressLine1:'',addressLine2:'',city:'',state:'',postalCode:'',country:'India'}),[msg,setMsg]=useState('');const load=()=>api('/api/addresses').then(setList).catch(x=>setMsg(x.message));useEffect(load,[]);const add=async e=>{e.preventDefault();try{await api('/api/addresses',{method:'POST',body:JSON.stringify(form)});setForm({...form,fullName:'',phone:'',addressLine1:'',addressLine2:'',city:'',state:'',postalCode:''});load()}catch(x){setMsg(x.message)}};const del=async id=>{await api(`/api/addresses/${id}`,{method:'DELETE'});load()};return <section><span className="eyebrow">ACCOUNT</span><h2>Delivery addresses</h2><div className="two"><form className="card" onSubmit={add}><h3>Add address</h3>{['fullName','phone','addressLine1','addressLine2','city','state','postalCode'].map(k=><input key={k} placeholder={k.replace(/([A-Z])/g,' $1')} value={form[k]} required={k!=='addressLine2'} onChange={e=>setForm({...form,[k]:e.target.value})}/>)}<button className="primary">Save address</button></form><div>{list.map(a=><div className="card address" key={a.id}><b>{a.fullName}</b><p>{a.addressLine1}{a.addressLine2&&`, ${a.addressLine2}`}<br/>{a.city}, {a.state} {a.postalCode}<br/>{a.phone}</p><button className="linkbtn danger" onClick={()=>del(a.id)}>Delete</button></div>)}{!list.length&&<div className="empty card">No saved addresses.</div>}</div></div>{msg&&<div className="error">{msg}</div>}</section>}
function Seller(){const [dash,setDash]=useState(null),[products,setProducts]=useState([]),[orders,setOrders]=useState([]),[msg,setMsg]=useState('');const load=async()=>{try{setDash(await api('/api/seller/dashboard'));setProducts(await api('/api/products/seller/my-products'));setOrders(await api('/api/seller/orders'))}catch(x){setMsg(x.message)}};useEffect(()=>{load()},[]);const stock=async p=>{const q=prompt(`New stock for ${p.name}`,p.quantity??p.stockQuantity);if(q===null)return;try{await api(`/api/products/${p.id}/inventory`,{method:'PUT',body:JSON.stringify({quantity:Number(q)})});load()}catch(x){setMsg(x.message)}};const status=async(o,s)=>{try{await api(`/api/seller/orders/${o.orderId||o.id}/status`,{method:'PUT',body:JSON.stringify({status:s})});load()}catch(x){setMsg(x.message)}};return <section><span className="eyebrow">SELLER CONSOLE</span><h2>Seller dashboard</h2>{msg&&<div className="error">{msg}</div>}{dash&&<div className="metrics">{[['Products',dash.totalProducts],['Orders',dash.totalOrders],['Placed',dash.placedOrders],['Confirmed',dash.confirmedOrders],['Shipped',dash.shippedOrders],['Delivered',dash.deliveredOrders],['Sales',money(dash.totalSales)]].map(([k,v])=><div className="metric card" key={k}><small>{k}</small><strong>{v}</strong></div>)}</div>}<div className="two sellergrid"><div><h3>Inventory</h3>{products.map(p=><div className="rowcard card" key={p.id}><div><b>{p.name}</b><small>{p.category} · {money(p.price)}</small></div><span>{p.quantity??p.stockQuantity}</span><button className="secondary" onClick={()=>stock(p)}>Update</button></div>)}</div><div><h3>Orders</h3>{orders.map(o=><div className="rowcard card" key={o.orderId||o.id}><div><b>Order #{o.orderId||o.id}</b><small>{o.customerName}</small></div><span className={`status ${String(o.status).toLowerCase()}`}>{o.status}</span><select value={o.status} onChange={e=>status(o,e.target.value)}><option>PLACED</option><option>CONFIRMED</option><option>SHIPPED</option><option>DELIVERED</option><option>CANCELLED</option></select></div>)}</div></div></section>}
function Admin(){const [users,setUsers]=useState([]),[products,setProducts]=useState([]),[msg,setMsg]=useState('');useEffect(()=>{Promise.all([api('/api/admin/users'),api('/api/admin/products')]).then(([u,p])=>{setUsers(u);setProducts(p)}).catch(x=>setMsg(x.message))},[]);const toggle=async p=>{try{await api(`/api/admin/products/${p.id}/${p.active?'deactivate':'activate'}`,{method:'PUT'});setProducts(await api('/api/admin/products'))}catch(x){setMsg(x.message)}};return <section><span className="eyebrow">ADMIN</span><h2>Marketplace control</h2>{msg&&<div className="error">{msg}</div>}<h3>Users</h3><div className="table card">{users.map(u=><div className="tablerow" key={u.id}><span>{u.fullName}</span><span>{u.email}</span><b>{u.role}</b></div>)}</div><h3>Products</h3><div className="table card">{products.map(p=><div className="tablerow" key={p.id}><span>{p.name}</span><span>{money(p.price)}</span><b>{p.active?'Active':'Inactive'}</b><button className="secondary" onClick={()=>toggle(p)}>{p.active?'Deactivate':'Activate'}</button></div>)}</div></section>}
function NotFound(){return <div className="empty card"><h2>Page not found</h2><Link to="/shop">Go shopping</Link></div>}
createRoot(document.getElementById('root')).render(<BrowserRouter><Layout/></BrowserRouter>)
